theme: jekyll-theme-minimal

title: Cong Nguyen Blog
description: Sharing knowledge for better develop
author: Cong Nguyen
email: congnt24@gmail.com

github_username:  congnt24

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

excerpt_separator: "<!--more-->"

disqus:
  shortname: congnt24-github-io
# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
# Seo
gems:
  - jekyll-seo-tag


