theme: jekyll-theme-minimal

title: Welcome to Cong Nguyen BLog
description: Sharing knowledge for better develop
author: Congnt24
email: congnt24@gmail.com

github_username:  congnt24

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock

